pipeline {
    agent none
    triggers {
        GenericTrigger(
             genericVariables: [
              [key: 'ref', value: '$.ref']
             ],
             genericHeaderVariables: [
              [key: 'X-Github-Event', regexpFilter: 'push']
             ],

             causeString: 'Triggered on the branch $ref',

             token: 'abc123',

             printContributedVariables: true,
             printPostContent: true,

             silentResponse: false,

             regexpFilterText: '$ref',
        )
    }
    stages {
        stage('check trigger vars') {
            steps {
                echo "$ref"
            }
        }

        stage('build') {
            agent { docker { image 'node:12.13.0-alpine' } }
            steps {
                sh 'npm --version'
                sh 'node --version'
                sh 'ls'
            }
        }

        stage('Stagging approval') {
            steps {
                input "Push to staging??"
            }
        }

        stage('Staging') {
            steps {
                echo "staging"
            }
        }
        
        stage('Production approval') {
            steps {
                input "Push to production?"
            }
        }
        
        stage('Deploy') {
            steps {
                echo "Deploying"
            }
        }    
    }
    post {
        success {
            echo 'Job Succeed'
        }
        failure {
            echo 'Job Failure'
        }
    }
}
