const users = [
    {
        id: 'jfdsflskgdjlvjlk', //generated by db
        username: 'CoolGuy28',  //username on platform
        email: 'Coolio23@gmail.com', //email on platform
        password: 'loll123', //obviously will be encrypted
        date_created: '02/24/19 12:43:38 EST', //date account was created on platform
        league_name: 'Elo over friends', //league of legends display name
        server: 'NA',
        rank: 21, //platinum 5 
        profile_pic: 'profile-pic-1.png',
        friends: [ //friends
            'fncneknwkjrhwekjhe', //second user after this current user (look at the id of second user)
            '',
            ''
        ],
        tournaments_participating: [ //tournaments being participated in
            {
                tournament_id:'efsjfewlejfelkf', //tournament id
                team_id: 'cndskjnckdsncdkjcsd' //team's id
            },
            {
                tournament_id:'sadasdasdasadetwe', 
                team_id: 'casfssdlfljssldl'
            }
        ],
        tournaments_participated: [ //tournaments already participated in
            {
                tournament_id:'fjsdfljdlkcmdlcfsdfs', 
                team_id: 'fskdhfskjdnvdskkj'
            },
            {
                tournament_id:'cdsfndfnkjsnckjsc', 
                team_id: 'vjndnvkjavnaknad'
            },
            {
                tournament_id:'fdslkfjsdcmdlkscdsmcl', 
                team_id: 'dfhsdkfjhsdkfhksd'
            }
        ]
    },
    {
        id: 'fncneknwkjrhwekjhe', //generated by db
        username: 'Marv223', 
        email: 'Marvin2314@yahoo.com',
        password: 'marvvv123', //obviously will be encrypted
        date_created: '02/24/19 12:43:38 EST',
        league_name: 'Rush dog',
        server: 'NA',
        rank: 15, //silver 1
        profile_pic: 'profile-pic-2.png',
        friends: ['jfdsflskgdjlvjlk','',''],
        tournaments_participating: [
            {
                tournament_id:'efsjfewlejfelkf', 
                team_id: 'xdlvskmglsdkfmsl'
            },
            {
                tournament_id:'sadasdasdasadetwe', 
                team_id: 'casfssdlfljssldl'
            }
        ],
        tournaments_participated: [
            {
                tournament_id:'vdfsldkjfslfmcdsdf', 
                team_id: 'dlvmdmlkcmsdlkscd'
            },
            {
                tournament_id:'cdsfndfnkjsnckjsc', 
                team_id: 'vjndnvkjavnaknad'
            },
            {
                tournament_id:'cmldskflejerlkjr', 
                team_id: 'vdsmvfdsjfljsdflfds'
            }
        ]
    }
]

const tournaments = [
    {
        id: 'efsjfewlejfelkf',
        num_teams: 24,
        team_ids: [
            'cndskjnckdsncdkjcsd',
            'xdlvskmglsdkfmsl' //there will obviously be 22 more teams but im too lazy to type them out lol
        ],
        standings: [], //ongoing tournament
        team_brackets: 'nvkjesdnefkenkewfn',
        date_created:   '02/20/19 12:43:38 EST',
        date_starting:  '03/10/19 15:00:00 EST',
        date_finished:  null //not finished yet
    },
    {
        id: 'sadasdasdasadetwe',
        num_teams: 8,
        team_ids: [
            'casfssdlfljssldl' //there will obviously be 7 more teams but im too lazy to type them out lol
        ],
        standings: [], //ongoing tournament
        team_brackets: 'csndkjnfksjefhkjkje',
        date_created:   '02/24/19 12:43:38 EST',
        date_starting:  '03/12/19 18:00:00 EST',
        date_finished:  null
    },
    {
        id: 'fjsdfljdlkcmdlcfsdfs',
        num_teams: 48,
        team_ids: [
            'fskdhfskjdnvdskkj' //there will obviously be 47 more teams but im too lazy to type them out lol
        ],
        standings: [], //ongoing tournament
        team_brackets: 'dleeryiwuryeiwuerw',
        date_created:   '02/24/19 12:43:38 EST',
        date_starting:  '02/25/19 15:00:00 EST',
        date_finished:  '02/26/19 11:35:03 EST'
    },
    {
        id: 'cdsfndfnkjsnckjsc',
        num_teams: 34,
        team_ids: [
            'vjndnvkjavnaknad'
        ],
        standings: [], //ongoing tournament
        team_brackets: 'etueriowuoeiruowi',
        date_created:   '02/10/19 12:43:38 EST',
        date_starting:  '02/19/19 09:00:00 EST',
        date_finished:  '02/22/19 11:35:03 EST' 
    },
    {
        id: 'fdslkfjsdcmdlkscdsmcl',
        num_teams: 12,
        team_ids: [
            'dfhsdkfjhsdkfhksd'
        ],
        standings: [], //ongoing tournament
        team_brackets: 'oeproweriepwoiweorw',
        date_created:   '01/05/19 12:43:38 EST',
        date_starting:  '01/11/19 12:00:00 EST',
        date_finished:  '01/13/19 11:35:03 EST' 
    },
    {
        id: 'vdfsldkjfslfmcdsdf',
        num_teams: 10,
        team_ids: [
            'dlvmdmlkcmsdlkscd' 
        ],
        standings: [], //ongoing tournament
        team_brackets: 'mfeifwejfowjfoweifjf',
        date_created:   '02/02/19 12:43:38 EST',
        date_starting:  '02/04/19 14:30:00 EST',
        date_finished:  '02/05/19 05:39:40 EST'
    },
    {
        id: 'cmldskflejerlkjr',
        num_teams: 14,
        team_ids: [
            'vdsmvfdsjfljsdflfds'
        ],
        standings: [], //ongoing tournament
        team_brackets: 'sfejfiwoejfewiffef',
        date_created:   '02/05/19 12:43:38 EST',
        date_starting:  '02/11/19 19:30:00 EST',
        date_finished:  '02/12/19 14:34:03 EST'
    }
]

const teams = [
    {
        id: 'cndskjnckdsncdkjcsd',
        name: 'Jackos Rackos',
        average_rank: 'Silver I' //this will be a number (number 15 since Iron 5-1 + Bronze 5-1 + Silver 5-1 = 15th. Silver 2 would be 14, etc)
    },
    {
        id: 'casfssdlfljssldl',
        name: 'Killer Instinct',
        average_rank: 'Gold IV' 
    },
    {
        id: 'xdlvskmglsdkfmsl',
        name: 'Team Tilters',
        average_rank: 'Platinum V' 
    },
    {
        id: 'vjndnvkjavnaknad',
        name: 'Owned boys',
        average_rank: 'Gold V' 
    },
    {
        id: 'fskdhfskjdnvdskkj',
        name: 'The Sirens',
        average_rank: 'Silver III' 
    },
    {
        id: 'dfhsdkfjhsdkfhksd',
        name: 'Olafs Goats',
        average_rank: 'Silver II' 
    },
    {
        id: 'dlvmdmlkcmsdlkscd',
        name: 'One Tricks',
        average_rank: 'Bronze I' 
    },
    {
        id: 'vdsmvfdsjfljsdflfds',
        name: 'Tilted for life',
        average_rank: 'Bronze III' 
    }
]


const brackets = [
    {
        bracket_id: 'nvkjesdnefkenkewfn',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'csndkjnfksjefhkjkje',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'dleeryiwuryeiwuerw',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'etueriowuoeiruowi',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'oeproweriepwoiweorw',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'mfeifwejfowjfoweifjf',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    },
    {
        bracket_id: 'sfejfiwoejfewiffef',
        games: [
            {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null}
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'casjldjlaskjdlasjdl', winner: 'cndskjnckdsncdkjcsd'}, //there will be more games in this array obviously 
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            // {team_1: 'cndskjnckdsncdkjcsd', team_2: 'xdlvskmglsdkfmsl', winner: null},
            
        ]
    }
]


export {
    users,
    tournaments,
    teams,
    brackets
}